SET foreign_key_checks = 0;
drop table if exists affiliation;
drop table if exists directory_entry;
drop table if exists lis_authority;
drop table if exists registration_code;
drop table if exists tli_user_tli_role;
drop table if exists tli_role;
drop table if exists tli_party;
drop table if exists tli_collection;
drop table if exists refdata_value;
drop table if exists refdata_category;
drop table if exists refdata_relation;
drop table if exists additional_property;
drop table if exists additional_property_definition;
drop table if exists directory_entry_collections;
drop table if exists directory_entry_subjects;
drop table if exists tli_location;
drop table if exists tli_session;

SET foreign_key_checks = 1;
